apply plugin: 'java-library'

repositories {
    mavenCentral()
}

dependencies {
    api 'com.google.code.gson:gson:2.9.0'
    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'org.slf4j:slf4j-api:2.0.17'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.vmlens:concurrent-junit:1.0.2'
    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
